# Generated by Django 4.2.27 on 2026-02-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oblik", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicemember",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
