# Generated by Django 4.2.27 on 2026-02-12 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("oblik", "0002_servicemember_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicemember",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
