# Generated by Django 4.2.27 on 2026-02-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oblik", "0003_servicemember_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("can_view_subordinates", models.BooleanField(default=False)),
                ("can_edit_subordinates", models.BooleanField(default=False)),
                ("can_add_personnel", models.BooleanField(default=False)),
                ("can_delete_personnel", models.BooleanField(default=False)),
                ("command_level", models.IntegerField(default=1)),
            ],
        ),
    ]
