# Generated by Django 4.2.27 on 2026-02-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oblik", "0004_accessprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="access_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="oblik.accessprofile",
            ),
        ),
    ]
