# Generated by Django 4.2.27 on 2026-02-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oblik", "0005_position_access_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="access_profile",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.PROTECT,
                to="oblik.accessprofile",
            ),
            preserve_default=False,
        ),
    ]
