from django.urls import path

from oblik.views import (index, Units_List_View, Service_Members_List_View,
                         Service_Members_Detail_View, test_session_view,
                         ServiceManCreateView, Units_List_Create_View,
                         Units_Update_View, Units_Delete_View, Ranks_List_View,
                         Rank_Create_View, Rank_Update_View, Rank_Delete_View,
                         Positions_List_View, Position_Create_View,
                         Position_Update_View, Position_Delete_View,
                         Service_Member_Update_View, Service_Member_Delete_View,
                         register_view, Units_Detail_View) #Create_User_View)

urlpatterns = [
    path("", index, name="index"),
    path("ranks/",
         Ranks_List_View.as_view(),
         name="ranks_list"),
    path("ranks/create",
         Rank_Create_View.as_view(),
         name="rank_create"),
    path("ranks/<int:pk>/update/",
         Rank_Update_View.as_view(),
         name="rank_update"),
    path("ranks/<int:pk>/delete/",
         Rank_Delete_View.as_view(),
         name="rank_delete"),
    path("positions/",
         Positions_List_View.as_view(),
         name="positions_list"),
    path("positions/create",
         Position_Create_View.as_view(),
         name="position_create"),
    path("positions/<int:pk>/update/",
         Position_Update_View.as_view(),
         name="position_update"),
    path("positions/<int:pk>/delete/",
         Position_Delete_View.as_view(),
         name="position_delete"),
    path("units_list/",
         Units_List_View.as_view(),
         name="units_list"),
    path("units_list/create/",
         Units_List_Create_View.as_view(),
         name="units_create"),
    path("units_list/<int:pk>/update/",
         Units_Update_View.as_view(),
         name="units_update"),
    path("units_list/<int:pk>/delete/",
         Units_Delete_View.as_view(),
         name="units_delete"),
    path("units_list/<int:pk>/",
         Units_Detail_View.as_view(),
         name="unit_detail"),
    # path("create_user/",
    #      Create_User_View.as_view(),
    #      name="create_user"),
    path("service_members/",
         Service_Members_List_View.as_view(),
         name="service_members_list"),
    path("service_members/create/", ServiceManCreateView.as_view(),
         name="service_man_create"),
    path("service_members/<int:pk>/update/",
         Service_Member_Update_View.as_view(),
         name="service_member_update"),
    path("service_members/<int:pk>/delete/",
         Service_Member_Delete_View.as_view(),
         name="service_member_delete"),
    path("service_members/<int:pk>/",
         Service_Members_Detail_View.as_view(),
         name="service_member_detail"),
    path("test_session/",
         test_session_view,
         name="test_session"),
    path("register/", register_view, name="register")
]

app_name = "oblik"